### ISSUE TITLE
I added your subs to a fanmade video featuring the ep. 12.4 "Japari bun hunt"

### ISSUE THREAD

**Issue by Seedmanc** [vacaran2017/vacaran2017.github.io#21]
4taba is down so I couldn't message you there, hence I'm using the Issues, you can close it after viewing.

![image](https://user-images.githubusercontent.com/8918278/51086155-fa441100-1753-11e9-9df0-28b55271a7a6.png)
Just thought you'd be interested to know that I found a video on niconico where various cuts from the KF anime were put together to create a fitting videotrack for the audiodorama "Japarimangari". I used that video, retouched it and added your translation of that episode with some edits and my typesetting so that now we have a complete new episode available here: https://www.youtube.com/watch?v=qn5rBwocrMg
Also mirrors in case YT goes down: https://vimeo.com/311055110 https://www.nicovideo.jp/watch/sm34469289 

Thanks for your work.

**Comment by vacaran2017** [comment]
Ah, that's lovely. Do you believe there is worth in merging your changes into the version here?

**Comment by Seedmanc** [comment]
#22 Okay, I tried to make a PR, but it wasn't being made with that in mind, see if it's okay. I believe your version can make use of typesetting and actor/style markup to see who's talking, mine has it.

**Comment by vacaran2017** [comment]
Merged! Sorry for taking so long again 🙇 I included your text where it differed, made a few corrections to my own text, changed the formatting of the lines, and kept most aspects of your typesetting.
